# This script concatenates multiple LMDB datasets generated by
# preprocess/process_EEG_fMRI_align.py into a single LMDB.

# ONLY supports new LMDB format (after Mar.2 commit)

"""
!!! WARNING:
    This script is intended to generate LMDB with multiple THINGS EEG
    subjects' data for E2E training -> testing out EEG encoder + MindEYE2 backend

    The generated LMDB would be compatible with align dataset BUT
    NOT intended to use for alignment task
"""

# NOTE:
#   1. Train / val / test splits are preserved: samples from each source
#      LMDB keep their original split assignment.
#      WARNING: potential data leakage (in case of different clustering results)
#   2. No EEG source tracking — samples are simply concatenated.
#      WARNING: we cannot backtrack which subject an EEG sample sourced.
#  
#   -> Output directory follows naming convention:
#      concat_things_<subjects>[_nsd_removed][_no_things_test]_<freq>Hz
#      >> placed under <processed_dir>/eeg_fmri_align_datasets/

# Import necessary libraries
import os
import lmdb
import pickle
from tqdm import tqdm
import typing

# --------------- Start of configuration --------------- #

# Root directory for processed datasets
processed_dir = "datasets/processed"

# Tuple of source LMDB directories to concatenate.
# Each must have been generated by preprocess/process_EEG_fMRI_align.py.
source_lmdb_dirs = (
    "datasets/processed/eeg_fmri_align_datasets/things_sub-01_nsd_sub-01_sub-02_sub-05_sub-07_no_things_test_250Hz",
)

# Whether to strip NSD data from the concatenated LMDB.
# When True, nsd_data is replaced with an empty list for each sample.
remove_nsd_data = False

# LMDB map size for the output database
lmdb_map_size = 53687091200

# ---------------- End of configuration ---------------- #

# Read meta_info from an LMDB dataset
def read_meta_info(lmdb_dir: str) -> typing.Dict[str, typing.Any]:

    """
    Read the meta_info entry from an LMDB dataset.
    """

    db = lmdb.open(lmdb_dir, 
                   readonly = True, lock = False, readahead = False, meminit = False)
    with db.begin(write=False) as txn:
        raw = txn.get('meta_info'.encode())
        if raw is None:
            raise ValueError(f"No meta_info found in LMDB at {lmdb_dir}")
        meta = pickle.loads(raw)
    db.close()
    return meta

# Collect keys from an LMDB dataset, grouped by split (train/val/test).
def collect_keys_by_split(lmdb_dir: str) -> typing.Dict[str, typing.List[str]]:

    """
    Return a dict mapping split name -> sorted list of keys.
    """

    db = lmdb.open(lmdb_dir, 
                   readonly = True, lock = False, readahead = False, meminit = False)
    split_keys = {'train': [], 'val': [], 'test': []}
    with db.begin(write = False) as txn:
        for raw_key, _ in txn.cursor():
            key = raw_key.decode()
            for split in split_keys:
                if key.startswith(split + '_'):
                    split_keys[split].append(key)
                    break
    db.close()
    for split in split_keys:
        split_keys[split].sort()
    return split_keys

# main function
def main():

    # Warn user about the purpose of this script
    print("\033[91mWARNING: This script concatenates multiple LMDB datasets (optionally keeps NSD pairings). "
          "The output LMDB might NOT be intended for alignment tasks and may contain data leakage across splits.\033[0m")
    print("Proceeding with concatenation...\n")

    # Validate source directories
    if not source_lmdb_dirs:
        raise ValueError("source_lmdb_dirs must contain at least one directory.")

    # collect meta_info from all sources
    all_meta = []
    for d in source_lmdb_dirs:
        if not os.path.exists(d):
            raise FileNotFoundError(f"Source LMDB directory not found: {d}")
        meta = read_meta_info(d)
        all_meta.append(meta)
        print(f"\033[92mLoaded meta_info from {d}\033[0m")
        print(f"  things_subject = {meta.get('things_subject')}")
        print(f"  nsd_subjects   = {meta.get('nsd_subjects')}")

    # Auto-detect THINGS EEG subjects
    things_subjects = sorted(set(
        m['things_subject'] for m in all_meta if 'things_subject' in m
    ))
    if not things_subjects:
        raise ValueError("Could not detect any THINGS subjects from source LMDBs.")
    print(f"\n\033[92mDetected THINGS subjects: {things_subjects}\033[0m")

    # Detect EEG target frequency from the first source's sample.
    # In this project the EEG is resampled so that the number of
    # timepoints equals TARGET_FREQ (e.g. 250 Hz -> 250 timepoints).
    detected_freq = None
    db0 = lmdb.open(source_lmdb_dirs[0], 
                     readonly = True, lock = False, readahead = False, meminit = False)
    with db0.begin(write = False) as txn:
        for raw_key, raw_val in txn.cursor():
            key = raw_key.decode()
            if key.startswith('train_') or key.startswith('val_') or key.startswith('test_'):
                sample = pickle.loads(raw_val)
                detected_freq = sample['eeg'].shape[-1]  # timepoints == TARGET_FREQ
                break
    db0.close()
    if detected_freq is None:
        raise ValueError("Could not detect EEG frequency from source LMDB samples.")
    print(f"Detected EEG target frequency: {detected_freq} Hz (timepoints)")

    # Check if THINGS test split was filtered in all sources
    all_exclude_test = all(m.get('exclude_THINGS_test_split', False) for m in all_meta)
    any_exclude_test = any(m.get('exclude_THINGS_test_split', False) for m in all_meta)
    if any_exclude_test and not all_exclude_test:
        print("\033[93mWarning: Not all sources agree on exclude_THINGS_test_split. "
              "Using '_no_things_test' only if ALL sources have it.\033[0m")

    # Construct output directory name
    things_tag = "_".join(things_subjects)
    nsd_removed_tag = "_nsd_removed" if remove_nsd_data else ""
    test_suffix = "_no_things_test" if all_exclude_test else ""
    output_dir_name = f"concat_things_{things_tag}{nsd_removed_tag}{test_suffix}_{detected_freq}Hz"
    output_dir = os.path.join(processed_dir, "eeg_fmri_align_datasets", output_dir_name)

    if os.path.exists(output_dir):
        print(f"\033[93mOutput directory {output_dir} already exists. Removing it ...\033[0m")
        import shutil
        shutil.rmtree(output_dir)
    os.makedirs(output_dir, exist_ok = True)
    print(f"\n>>> Output LMDB will be written to: {output_dir}")

    # Open concat LMDB for writing
    db_out = lmdb.open(output_dir, map_size=lmdb_map_size)

    # Write meta_info
    # WARNING: differs from alignment meta_info !!!
    concat_meta = {
        'things_subjects': things_subjects,
        'remove_nsd_data': remove_nsd_data,
        'exclude_THINGS_test_split': all_exclude_test,
        'source_lmdb_dirs': list(source_lmdb_dirs),
    }
    txn = db_out.begin(write = True)
    txn.put(key='meta_info'.encode(), value = pickle.dumps(concat_meta))
    txn.commit()

    WRITE_BATCH_SIZE = 1000  # commit every N writes for efficiency

    total_counts = {'train': 0, 'val': 0, 'test': 0}

    for src_idx, src_dir in enumerate(source_lmdb_dirs):
        print(f"\n>>> Reading source {src_idx + 1}/{len(source_lmdb_dirs)}: {src_dir}")
        split_keys = collect_keys_by_split(src_dir)
        db_src = lmdb.open(src_dir, 
                           readonly = True, lock = False, readahead = True, meminit = False)

        for split in ('train', 'val', 'test'):
            keys = split_keys[split]
            if not keys:
                continue
            print(f"  {split}: {len(keys)} samples")

            txn_w = db_out.begin(write = True)
            batch_count = 0
            for key in tqdm(keys, desc = f"  Copying {split}"):
                # Read original sample
                with db_src.begin(write = False) as txn_r:
                    sample = pickle.loads(txn_r.get(key.encode()))

                # Optionally remove NSD data
                if remove_nsd_data:
                    sample['nsd_data'] = []

                # Write with new sequential index
                # New key format: <split>_<6-digit zero-padded index>_00000
                new_key = f"{split}_{total_counts[split]:05d}_00000"
                txn_w.put(key = new_key.encode(), value = pickle.dumps(sample))
                total_counts[split] += 1
                batch_count += 1

                # Commit every WRITE_BATCH_SIZE samples for efficiency
                if batch_count >= WRITE_BATCH_SIZE:
                    txn_w.commit()
                    txn_w = db_out.begin(write = True)
                    batch_count = 0

            # Commit any remaining samples after the loop
            txn_w.commit()

        # close LMDB source
        db_src.close()
    
    # close concat LMDB
    db_out.close()

    print(f"\n\033[92mConcatenation complete. Output at: {output_dir}\033[0m")
    print(f"Total samples written: {total_counts}")

    # Sanity check the created LMDB
    print(f"\nSanity check for the created LMDB dataset at {output_dir}...")
    db = lmdb.open(output_dir, readonly = True, lock = False, readahead = True, meminit = False)
    with db.begin(write = False) as txn:
        keys = [key.decode() for key, _ in txn.cursor()]
    print(f"Total entries in LMDB: {len(keys)} ({len(keys) - 1} samples + meta_info)")

    split_counts = {'train': 0, 'val': 0, 'test': 0}
    for key in keys:
        for s in split_counts:
            if key.startswith(s + '_'):
                split_counts[s] += 1
    print(f"Sample counts by split: {split_counts}")

    # Verify a sample structure
    with db.begin(write = False) as txn:
        sample_keys = [k for k in keys if k.startswith('train_')]
        if sample_keys:
            sample = pickle.loads(txn.get(sample_keys[0].encode()))
            print(f"Sample structure keys: {list(sample.keys())}")
            print(f"  EEG shape: {sample['eeg'].shape}")
            print(f"  nsd_data entries: {len(sample['nsd_data'])}")
            if sample['nsd_data']:
                for nd in sample['nsd_data']:
                    print(f"    subject = {nd['subject']}, fmri shape = {nd['fmri'].shape}, "
                          f"nsd_img_idx = {nd['nsd_img_idx']}")
            else:
                print(f"    (NSD data removed)")

    # Verify meta_info
    with db.begin(write = False) as txn:
        meta = pickle.loads(txn.get('meta_info'.encode()))
        print(f"Concatenated meta_info: {meta}")

    db.close()
    print(f"\nDone concatenating.\n\033[92mFinal output LMDB is ready at: {output_dir}\033[0m")


if __name__ == '__main__':
    main()